version: '3'
services:
  db:
    image: postgres:16-alpine
    environment:
      - HOST_NEWS_TAG=http://notreal/predict
      - HOST_SUMMARY=http://notreal/api/generate
    network_mode: "host"
    ports:
      - "5000:5000"
    volumes:
      - /data/:/var/lib/postgresql/data
